[package]
name = "file_reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.6"
curl = "0.4.43"
polars = "0.20.0"
reqwest = "0.11.10"
